import os
import shutil

ORIGEM = "public/images/descomplicaí banco de imagens"
DESTINO = "public/images"

# Criar todas as pastas
pastas = [
    "flores", "vestidos", "traje-noivo", "mesa", "decoracao",
    "cerimonia", "local", "alimentacao", "entretenimento",
    "beleza", "papelaria", "detalhes", "planejamento"
]

for pasta in pastas:
    os.makedirs(os.path.join(DESTINO, pasta), exist_ok=True)

movidos = 0
nao_encontrados = 0

def mover(nome_origem, destino_relativo):
    global movidos, nao_encontrados
    
    # Procura o arquivo em qualquer subpasta
    origem_caminho = None
    for raiz, dirs, arquivos in os.walk(ORIGEM):
        if nome_origem in arquivos:
            origem_caminho = os.path.join(raiz, nome_origem)
            break
    
    destino_caminho = os.path.join(DESTINO, destino_relativo)
    
    if origem_caminho and os.path.exists(origem_caminho):
        shutil.move(origem_caminho, destino_caminho)
        print(f"✓ {nome_origem} → {destino_relativo}")
        movidos += 1
    else:
        print(f"✗ NÃO ENCONTRADO: {nome_origem}")
        nao_encontrados += 1

# ========== FLORES ==========
mover("annie-spratt-01Wa3tPoQQ8-unsplash.jpg", "flores/rosas-1.jpg")
mover("annie-spratt-gpese6ZRQsE-unsplash.jpg", "flores/rosas-2.jpg")
mover("annie-spratt-LXpk9bLpwSo-unsplash.jpg", "flores/rosas-3.jpg")
mover("annie-spratt-x4YEK7o8L0c-unsplash.jpg", "flores/rosas-4.jpg")
mover("annie-spratt-XkTIgaEy9IM-unsplash.jpg", "flores/rosas-5.jpg")
mover("seljan-salimova-rKV2De7eeBQ-unsplash.jpg", "flores/rosas-6.jpg")
mover("meg-von-haartman-bUC51U1HWDY-unsplash.jpg", "flores/flores-secas-1.jpg")
mover("meg-von-haartman-JP7KJ2mhYiM-unsplash.jpg", "flores/flores-secas-2.jpg")
mover("mieke-campbell-_lmX02vePr4-unsplash.jpg", "flores/flores-do-campo-1.jpg")
mover("olena-bohovyk-6nG7m9AYbio-unsplash.jpg", "flores/flores-do-campo-2.jpg")
mover("pedro-pulido-LdpSdMmy29E-unsplash.jpg", "flores/flores-do-campo-3.jpg")
mover("alexander-mass-E1qBgWoC1XA-unsplash.jpg", "flores/flores-default-1.jpg")
mover("annie-gray-m7GoDeEvf1k-unsplash.jpg", "flores/flores-default-2.jpg")
mover("christina-victoria-craft-33EfiDWNIqk-unsplash.jpg", "flores/flores-default-3.jpg")
mover("christina-victoria-craft-K64N6WkhL4g-unsplash.jpg", "flores/flores-default-4.jpg")
mover("david-holifield-8LxfHrlL4N4-unsplash.jpg", "flores/flores-default-5.jpg")
mover("david-holifield-1vdmsiyX9W8-unsplash.jpg", "flores/flores-default-6.jpg")
mover("david-holifield-Jb9WQIvR4YQ-unsplash.jpg", "flores/flores-default-7.jpg")
mover("diana-light-w9KrnZBTKds-unsplash.jpg", "flores/flores-default-8.jpg")
mover("diana-light-X6t0EmzKjm4-unsplash.jpg", "flores/flores-default-9.jpg")
mover("joshua-soliz-61UcuU8DqLQ-unsplash.jpg", "flores/flores-default-10.jpg")
mover("karolina-bobek-XQgTY7j2uEk-unsplash.jpg", "flores/flores-default-11.jpg")
mover("kyle-vaughn-i3ka9q7EhH8-unsplash.jpg", "flores/flores-default-12.jpg")
mover("liviu-boldis-ZXO5V0qZJGU-unsplash.jpg", "flores/flores-default-13.jpg")
mover("maryna-vladymyrska-S7fu0-EmIFg-unsplash.jpg", "flores/flores-default-14.jpg")
mover("natali-hordiiuk-UMHU7OWEFT0-unsplash.jpg", "flores/flores-default-15.jpg")
mover("quilia-CeKaBzyvxxI-unsplash.jpg", "flores/flores-default-16.jpg")
mover("reba-spike-mSvE3JD1d0U-unsplash.jpg", "flores/flores-default-17.jpg")
mover("samantha-gades-_TiUsIrO7ds-unsplash.jpg", "flores/flores-default-18.jpg")
mover("samantha-gades-bFYoyKivbmg-unsplash.jpg", "flores/flores-default-19.jpg")
mover("samantha-gades-N1CZNuM_Fd8-unsplash.jpg", "flores/flores-default-20.jpg")
mover("stephen-wheeler-QjoXfAdqg8Q-unsplash.jpg", "flores/flores-default-21.jpg")
mover("thomas-william-nAvodiKjbTM-unsplash.jpg", "flores/flores-default-22.jpg")
mover("victoria-vandenberg-g4DeA8tVem0-unsplash.jpg", "flores/flores-default-23.jpg")
mover("wedding-dreamz-pqkn1uIS6jY-unsplash.jpg", "flores/flores-default-24.jpg")
mover("charlotte-cowell-IcE5fO92Gkc-unsplash.jpg", "flores/flores-do-campo-4.jpg")
mover("alexander-mass-w8FQnzd2fVg-unsplash.jpg", "flores/flores-do-campo-5.jpg")
mover("engin-akyurt-MeNE7Ockq4w-unsplash.jpg", "flores/flores-default-25.jpg")

# ========== VESTIDOS ==========
mover("helen-oreshchenko-7Z1xbz_OpYg-unsplash.jpg", "vestidos/vestido-minimalista-1.jpg")
mover("kura-tregenza-5JEbKNp9uNk-unsplash-(1).jpg", "vestidos/vestido-boho-1.jpg")
mover("kura-tregenza-5JEbKNp9uNk-unsplash.jpg", "vestidos/vestido-boho-2.jpg")
mover("maria-luisa-queiroz-iINBpyermdM-unsplash.jpg", "vestidos/vestido-minimalista-2.jpg")
mover("maria-luisa-queiroz-zT65ORHLCWg-unsplash.jpg", "vestidos/vestido-minimalista-3.jpg")
mover("wedmaid-dresses-E6WecF9asKA-unsplash.jpg", "vestidos/vestido-minimalista-4.jpg")
mover("jarvis-couture-bridal-prom-tyler-tx-HJWLIFZfozg-unsplash.jpg", "vestidos/vestido-default-1.jpg")
mover("rjer-dress-eRJ-vvdhbY4-unsplash.jpg", "vestidos/vestido-default-2.jpg")

# ========== TRAJE NOIVO ==========
mover("550park-luxury-wedding-films-ANqOsdiX1g8-unsplash.jpg", "traje-noivo/making-of-noivo-1.jpg")
mover("bruno-ngarukiye-19oFhgJIV40-unsplash.jpg", "traje-noivo/terno-noivo-1.jpg")
mover("bruno-ngarukiye-swTMHPN2ij0-unsplash.jpg", "traje-noivo/terno-noivo-2.jpg")
mover("bruno-ngarukiye-GNmYq9E3g_0-unsplash.jpg", "traje-noivo/terno-noivo-3.jpg")
mover("bruno-ngarukiye-YrThd1lBFu4-unsplash.jpg", "traje-noivo/terno-noivo-4.jpg")
mover("bruno-ngarukiye-bJPR7RsdBdU-unsplash.jpg", "traje-noivo/padrinhos-1.jpg")
mover("bruno-ngarukiye-t1ep0yUdXWw-unsplash.jpg", "traje-noivo/padrinhos-2.jpg")
mover("bruno-ngarukiye-XIilyZd6oU0-unsplash.jpg", "traje-noivo/padrinhos-3.jpg")
mover("bruno-ngarukiye-zZ4hsQfse7o-unsplash.jpg", "traje-noivo/padrinhos-4.jpg")
mover("brunxs-monochrome--QHtE6IsLK0-unsplash.jpg", "traje-noivo/making-of-noivo-2.jpg")
mover("hitesh-patel-H26dqHe9l2c-unsplash.jpg", "traje-noivo/terno-noivo-5.jpg")
mover("lucas-mendes-x-uBdVCcWQM-unsplash.jpg", "traje-noivo/terno-noivo-6.jpg")
mover("lucas-t-photography-eN1lACiHPfU-unsplash.jpg", "traje-noivo/terno-noivo-7.jpg")
mover("nikita-shirokov-7wjxyiUvt4I-unsplash.jpg", "traje-noivo/terno-noivo-8.jpg")
mover("prashant-raje-IT2k_Lcms4s-unsplash.jpg", "traje-noivo/terno-noivo-9.jpg")
mover("steward-masweneng-nUOpSNGiT1s-unsplash.jpg", "traje-noivo/terno-noivo-10.jpg")
mover("lucas-t-photography-Dfm_QyLkIlw-unsplash.jpg", "traje-noivo/making-of-noivo-3.jpg")

# ========== MESA ==========
mover("chalo-garcia-LOczKkVDRuI-unsplash.jpg", "mesa/mesa-classico-1.jpg")
mover("jonathan-borba-auBHpc1Ev-0-unsplash.jpg", "mesa/mesa-classico-2.jpg")
mover("miltiadis-fragkidis-1xX_I3tdvFg-unsplash.jpg", "mesa/mesa-classico-3.jpg")
mover("susanna-iovene-ip4WDb57fVY-unsplash.jpg", "mesa/mesa-classico-4.jpg")
mover("tim-pack-_sH9ifV2yjY-unsplash.jpg", "mesa/mesa-classico-5.jpg")
mover("yx-w-gCW6yLclSdI-unsplash.jpg", "mesa/mesa-classico-6.jpg")
mover("alexander-mass-6PDYITurN5Q-unsplash.jpg", "mesa/mesa-rustico-1.jpg")
mover("ivett-m-QLd2xe8oM9Q-unsplash.jpg", "mesa/mesa-rustico-2.jpg")
mover("pedro-pulido-iBpGNupUw5I-unsplash.jpg", "mesa/mesa-rustico-3.jpg")
mover("shoham-avisrur-XYdJWNy0jE4-unsplash.jpg", "mesa/mesa-rustico-4.jpg")
mover("soulseeker-creative-photography-bt5Br2xp1pU-unsplash.jpg", "mesa/mesa-rustico-5.jpg")
mover("soulseeker-creative-photography-HIJXSQnecNE-unsplash.jpg", "mesa/mesa-rustico-6.jpg")
mover("soulseeker-creative-photography-nX5Xfn65R6Y-unsplash.jpg", "mesa/mesa-rustico-7.jpg")
mover("soulseeker-creative-photography-SmaNINKn7Hs-unsplash.jpg", "mesa/mesa-rustico-8.jpg")
mover("ahmed-T3yHnPbbTmU-unsplash.jpg", "mesa/mesa-romantico-1.jpg")
mover("silvia-mara-y0u7nji4uXY-unsplash.jpg", "mesa/mesa-romantico-2.jpg")
mover("silvia-mara-0LC3ei-lqVQ-unsplash.jpg", "mesa/mesa-romantico-3.jpg")
mover("silvia-mara-JHNPqGKR9II-unsplash.jpg", "mesa/mesa-romantico-4.jpg")
mover("silvia-mara-MuZ9XVsH8yA-unsplash.jpg", "mesa/mesa-romantico-5.jpg")
mover("m-f-fb0_wj2MZk4-unsplash.jpg", "mesa/mesa-minimalista-1.jpg")
mover("mockaroon-RXRwpMI3FRA-unsplash.jpg", "mesa/mesa-minimalista-2.jpg")
mover("chuttersnap-aEnH4hJ_Mrs-unsplash.jpg", "mesa/mesa-default-1.jpg")
mover("karaz-pro-XAoHCa1GIns-unsplash.jpg", "mesa/mesa-default-2.jpg")

# ========== DECORAÇÃO ==========
mover("alvin-mahmudov-5N2tCRDWaLI-unsplash.jpg", "decoracao/decor-classico-1.jpg")
mover("alvin-mahmudov-NSVJAAXOYHs-unsplash.jpg", "decoracao/decor-classico-2.jpg")
mover("erika-fletcher-quKkhmldPJQ-unsplash.jpg", "decoracao/decor-classico-3.jpg")
mover("fotografo-samuel-cruz-8bFEqeV04KI-unsplash.jpg", "decoracao/decor-classico-4.jpg")
mover("jason-gardner-hiAlkxoq4kk-unsplash.jpg", "decoracao/decor-classico-5.jpg")
mover("jonathan-borba-8BCdYLKrzz8-unsplash.jpg", "decoracao/decor-classico-6.jpg")
mover("jonathan-borba-OJXHNc4FbZE-unsplash.jpg", "decoracao/decor-classico-7.jpg")
mover("jonathan-borba-P6_SrpAq97A-unsplash.jpg", "decoracao/decor-classico-8.jpg")
mover("kaushal-amrutiya-JkSskkZm3sY-unsplash.jpg", "decoracao/decor-classico-9.jpg")
mover("lucas-t-photography-T5v5i67QYGk-unsplash.jpg", "decoracao/decor-classico-10.jpg")
mover("nathan-walker-cVRgwcudqDU-unsplash.jpg", "decoracao/decor-classico-11.jpg")
mover("nathan-walker-T4wEATrTljY-unsplash.jpg", "decoracao/decor-classico-12.jpg")
mover("susanne-neumair-V3S4EaKv35o-unsplash.jpg", "decoracao/decor-classico-13.jpg")
mover("troy-olson-54GeflCREBs-unsplash.jpg", "decoracao/decor-classico-14.jpg")
mover("troy-olson-Gw2ODMZDeK4-unsplash.jpg", "decoracao/decor-classico-15.jpg")
mover("troy-olson-hXprYkqi9bs-unsplash.jpg", "decoracao/decor-classico-16.jpg")
mover("wedding-dreamz-iZit-SCQAdA-unsplash.jpg", "decoracao/decor-classico-17.jpg")
mover("yamasa-n-12Fyn3EJBrQ-unsplash.jpg", "decoracao/decor-classico-18.jpg")
mover("abby-savage-zNsSwsuyP3A-unsplash.jpg", "decoracao/decor-rustico-1.jpg")
mover("alexander-mass-45_VAB9qcAc-unsplash.jpg", "decoracao/decor-rustico-2.jpg")
mover("iskra-photography-iXTkKQyVqbM-unsplash.jpg", "decoracao/decor-rustico-3.jpg")
mover("jeppe-monster-yrwZZjer070-unsplash.jpg", "decoracao/decor-rustico-4.jpg")
mover("jose-marroquin-zWv16O3t2wI-unsplash.jpg", "decoracao/decor-rustico-5.jpg")
mover("kofookoo-de-6EgxRnKU5BI-unsplash.jpg", "decoracao/decor-rustico-6.jpg")
mover("mayank-baranwal-hqX2Ge-CJGQ-unsplash.jpg", "decoracao/decor-rustico-7.jpg")
mover("pedro-pulido-f7e3L3Fji9I-unsplash.jpg", "decoracao/decor-rustico-8.jpg")
mover("shing-Sn7DQPsUIp0-unsplash.jpg", "decoracao/decor-rustico-9.jpg")
mover("bridget-flohe-f5Y_m2bD_Tw-unsplash.jpg", "decoracao/decor-boho-1.jpg")
mover("jo-brady-XzOGEpVnktw-unsplash.jpg", "decoracao/decor-boho-2.jpg")
mover("alison-erickson-jPDRE3C4MbY-unsplash.jpg", "decoracao/decor-moderno-1.jpg")
mover("filipp-romanovski-uICRbCjNheY-unsplash.jpg", "decoracao/decor-moderno-2.jpg")
mover("filipp-romanovski-za66-riaVLo-unsplash.jpg", "decoracao/decor-moderno-3.jpg")
mover("kari-bjorn-photography-c0HhHzrSvMg-unsplash.jpg", "decoracao/decor-moderno-4.jpg")
mover("kari-bjorn-photography-fL9CZXS8SyQ-unsplash.jpg", "decoracao/decor-moderno-5.jpg")
mover("lee-brown-oMS5oyiqPbk-unsplash.jpg", "decoracao/decor-moderno-6.jpg")
mover("micheile-henderson-KWHoxdn1IUE-unsplash.jpg", "decoracao/decor-moderno-7.jpg")
mover("orio-nguyen-pTrHHGrxeOE-unsplash.jpg", "decoracao/decor-moderno-8.jpg")
mover("skyangel79-LTY6ZXRWRFw-unsplash.jpg", "decoracao/decor-moderno-9.jpg")
mover("zane-persaud-jLU-kQEUylE-unsplash.jpg", "decoracao/decor-moderno-10.jpg")
mover("aurela-redenica-9vHAhn_gUtg-unsplash.jpg", "decoracao/decor-minimalista-1.jpg")
mover("aurela-redenica-IT_zVqE__aU-unsplash.jpg", "decoracao/decor-minimalista-2.jpg")
mover("chasse-sauvage-cKupNvXrU4I-unsplash.jpg", "decoracao/decor-minimalista-3.jpg")
mover("chasse-sauvage-fSJSiczZBVQ-unsplash.jpg", "decoracao/decor-minimalista-4.jpg")
mover("hannah-busing-0BhSKStVtdM-unsplash.jpg", "decoracao/decor-minimalista-5.jpg")
mover("kyle-austin-ZK8u4kJlcfU-unsplash.jpg", "decoracao/decor-minimalista-6.jpg")
mover("logan-weaver-lgnwvr-G5RSe8i_Id8-unsplash.jpg", "decoracao/decor-minimalista-7.jpg")
mover("luwadlin-bosman-FFhZrVwkv6E-unsplash.jpg", "decoracao/decor-minimalista-8.jpg")
mover("obi-A2rLX0UWKio-unsplash.jpg", "decoracao/decor-minimalista-9.jpg")
mover("philip-smart-CY3D-UDknxY-unsplash.jpg", "decoracao/decor-minimalista-10.jpg")
mover("thomas-ae-295NLwGdrKM-unsplash.jpg", "decoracao/decor-minimalista-11.jpg")
mover("anna-bratiychuk-S16wIj4Wy2w-unsplash.jpg", "decoracao/decor-romantico-1.jpg")
mover("francesco-liotti-HDdIif4xdBg-unsplash.jpg", "decoracao/decor-romantico-2.jpg")
mover("freya-song-GG9eLN3Lu6A-unsplash.jpg", "decoracao/decor-romantico-3.jpg")
mover("david-kristianto-i4XQ0NBCWzU-unsplash.jpg", "decoracao/decor-default-1.jpg")
mover("denio-rodriguez-HBETvpRcRgA-unsplash.jpg", "decoracao/decor-default-2.jpg")
mover("marius-muresan-_cjEupOHCUQ-unsplash.jpg", "decoracao/decor-default-3.jpg")
mover("marius-muresan-goyjl9S-W5s-unsplash.jpg", "decoracao/decor-default-4.jpg")
mover("marius-muresan-qj2V_SKG6BM-unsplash.jpg", "decoracao/decor-default-5.jpg")
mover("marius-muresan-YspV19A7pAc-unsplash.jpg", "decoracao/decor-default-6.jpg")
mover("marius-pavel-pRYehYMb3UA-unsplash.jpg", "decoracao/decor-default-7.jpg")
mover("raissa-lara-lutolf-fasel-XsJJgnWXU-c-unsplash.jpg", "decoracao/decor-default-8.jpg")
mover("raphael-renter-raphi_rawr-JcQxk6dFtAM-unsplash.jpg", "decoracao/decor-default-9.jpg")
mover("raphael-renter-raphi_rawr-NKl3GUEbrFo-unsplash.jpg", "decoracao/decor-default-10.jpg")
mover("ridham-supriyanto-JRhhF0a4N-E-unsplash.jpg", "decoracao/decor-default-11.jpg")
mover("robert-vasquez-1Mnx6aWMouo-unsplash.jpg", "decoracao/decor-default-12.jpg")
mover("samuel-lopez-cruz-thdH4Mgnh-Y-unsplash.jpg", "decoracao/decor-default-13.jpg")
mover("virginia-berbece-eiwS39Poteg-unsplash.jpg", "decoracao/decor-default-14.jpg")

# ========== CERIMÔNIA ==========
mover("eric-brehm-t5PlRnsXy1I-unsplash.jpg", "cerimonia/cerimonia-altar-1.jpg")
mover("alexander-mass-A5XuNmUT2DE-unsplash.jpg", "cerimonia/cerimonia-altar-2.jpg")
mover("david-goldman-kdlfXY9rvZA-unsplash.jpg", "cerimonia/cerimonia-altar-3.jpg")
mover("david-goldman-KKTCngYYWFk-unsplash.jpg", "cerimonia/cerimonia-altar-4.jpg")
mover("fotografo-samuel-cruz-HCUWYG5gCCY-unsplash.jpg", "cerimonia/cerimonia-altar-5.jpg")
mover("gary-walker-jones-PMncgiAM-Dk-unsplash.jpg", "cerimonia/cerimonia-altar-6.jpg")
mover("giorgi-khatchapuridze-D6ZzpJZgkBs-unsplash.jpg", "cerimonia/cerimonia-altar-7.jpg")
mover("ikshana-productions-33RGcIhPQ14-unsplash.jpg", "cerimonia/cerimonia-altar-8.jpg")
mover("jeremy-wong-weddings-K41SGnGKxVk-unsplash.jpg", "cerimonia/cerimonia-altar-9.jpg")
mover("jonathan-borba-g-46CLKsDW8-unsplash.jpg", "cerimonia/cerimonia-altar-10.jpg")
mover("jonathan-borba-r-otbbSVAPc-unsplash.jpg", "cerimonia/cerimonia-altar-11.jpg")
mover("nicole-corbin-i4NqeIHNbTI-unsplash.jpg", "cerimonia/cerimonia-altar-12.jpg")
mover("fotografo-samuel-cruz-rcFAMXrMwnY-unsplash.jpg", "cerimonia/cerimonia-altar-13.jpg")
mover("salman-rameli-5Hc2c49D7jc-unsplash.jpg", "cerimonia/cerimonia-altar-14.jpg")
mover("sergei-kondalov-FKLXn1mw3Bg-unsplash.jpg", "cerimonia/cerimonia-altar-15.jpg")
mover("sushanta-rokka-0X7I1QwuirM-unsplash.jpg", "cerimonia/cerimonia-altar-16.jpg")
mover("thomas-christian-gs8kJSZxTVk-unsplash.jpg", "cerimonia/cerimonia-altar-17.jpg")
mover("victoria-priessnitz-SdfogwU9QnU-unsplash.jpg", "cerimonia/cerimonia-altar-18.jpg")
mover("zane-persaud-F_2bqTZ0Vl0-unsplash.jpg", "cerimonia/cerimonia-altar-19.jpg")
mover("alexander-mass-gjn-swBQWEA-unsplash.jpg", "cerimonia/cerimonia-corredor-1.jpg")
mover("fotografo-samuel-cruz-TsKGblZjQy4-unsplash.jpg", "cerimonia/cerimonia-corredor-2.jpg")
mover("guillaume-dhalluin-7enPZgey7vE-unsplash.jpg", "cerimonia/cerimonia-corredor-3.jpg")
mover("javier-reyes-J6a4hgVw-hM-unsplash.jpg", "cerimonia/cerimonia-corredor-4.jpg")
mover("junior-reis-xMDo8y776uE-unsplash.jpg", "cerimonia/cerimonia-corredor-5.jpg")
mover("omar-lopez-pkKdbtTwxAs-unsplash.jpg", "cerimonia/cerimonia-corredor-6.jpg")
mover("simply-thrilled-65mh04qlcBU-unsplash.jpg", "cerimonia/cerimonia-corredor-7.jpg")
mover("tomas-rekstad-NPg5_iVZQ2s-unsplash.jpg", "cerimonia/cerimonia-corredor-8.jpg")
mover("amin-samedov-F8kYxGg8bYk-unsplash.jpg", "cerimonia/cerimonia-saida-1.jpg")
mover("francesco-tommasini-E0ZdPFXqdDE-unsplash.jpg", "cerimonia/cerimonia-saida-2.jpg")
mover("michael-mcauliffe-YBzj70bym80-unsplash.jpg", "cerimonia/cerimonia-saida-3.jpg")
mover("photos-by-lanty-dcb2pog89fQ-unsplash.jpg", "cerimonia/cerimonia-saida-4.jpg")
mover("ray-shrewsberry-dqQL1yrzIto-unsplash.jpg", "cerimonia/cerimonia-saida-5.jpg")
mover("zane-persaud-3kMdd19x33A-unsplash.jpg", "cerimonia/cerimonia-saida-6.jpg")
mover("browne-and-dixon-photography-L0-ljI3V9UY-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-1.jpg")
mover("fotografo-samuel-cruz-6-mCjWwIJYk-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-2.jpg")
mover("ikshana-productions-UX3-_dGbCzk-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-3.jpg")
mover("katie-puzatova-w9hsioE2Zc4-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-4.jpg")
mover("lucas-t-photography-7K67WDBrcIs-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-5.jpg")
mover("monique-carrati-UGEQSGkyGj8-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-6.jpg")
mover("photos-by-lanty-O38Id_cyV4M-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-7.jpg")
mover("vitor-monthay-c9RoBYOHLeA-unsplash.jpg", "cerimonia/cerimonia-entrada-noiva-8.jpg")
mover("andres-molina-3BZeIDjq4Po-unsplash.jpg", "cerimonia/cerimonia-aliancas-1.jpg")
mover("leo_visions-TQT_NbJao5E-unsplash.jpg", "cerimonia/cerimonia-aliancas-2.jpg")
mover("tsuyoshi-kozu-ic4QaeuPONI-unsplash.jpg", "cerimonia/cerimonia-aliancas-3.jpg")
mover("cleyton-ewerton-bsOXve-idOY-unsplash.jpg", "cerimonia/cerimonia-beijo-1.jpg")
mover("fotografo-samuel-cruz-OMqS8FMgOvg-unsplash.jpg", "cerimonia/cerimonia-beijo-2.jpg")
mover("guy-basabose-xo318M8bemw-unsplash.jpg", "cerimonia/cerimonia-beijo-3.jpg")
mover("jonathan-borba-JmEGzp5elWA-unsplash.jpg", "cerimonia/cerimonia-beijo-4.jpg")
mover("jose-nicdao-H8eSYN9AyEs-unsplash.jpg", "cerimonia/cerimonia-beijo-5.jpg")
mover("kevin-hernandez-reyes-t53AQ1QlnnA-unsplash.jpg", "cerimonia/cerimonia-beijo-6.jpg")
mover("robert-vasquez-6zxZGGorb_0-unsplash.jpg", "cerimonia/cerimonia-beijo-7.jpg")
mover("yoav-franco-Am7cnuf_T7M-unsplash.jpg", "cerimonia/cerimonia-beijo-8.jpg")
mover("kylefromthenorth-divZsHxB0m4-unsplash.jpg", "cerimonia/cerimonia-assentos-1.jpg")

# ========== LOCAL ==========
mover("adrien-olichon-jds_OTZ8c7w-unsplash.jpg", "local/local-salao-1.jpg")
mover("alexander-mass-egFubUTSI6c-unsplash.jpg", "local/local-salao-2.jpg")
mover("ambitious-studio-rick-barrett-tegJMF_DdXU-unsplash.jpg", "local/local-salao-3.jpg")
mover("chris-dickens-pwJupDWJQ3s-unsplash.jpg", "local/local-salao-4.jpg")
mover("colton-sturgeon-Mc4TqYOiJlA-unsplash.jpg", "local/local-salao-5.jpg")
mover("eryk-piotr-munk-RlIa8AxVtv0-unsplash.jpg", "local/local-salao-6.jpg")
mover("fotografo-samuel-cruz-k0SyhTGHBjU-unsplash.jpg", "local/local-salao-7.jpg")
mover("francesco-liotti-Srus1IfxzUc-unsplash.jpg", "local/local-salao-8.jpg")
mover("jen-vazquez-4AX70fujoxg-unsplash.jpg", "local/local-salao-9.jpg")
mover("jonathan-borba-ONCGcee9Yt4-unsplash.jpg", "local/local-salao-10.jpg")
mover("les-taylor-PoSVFLPc-z4-unsplash.jpg", "local/local-salao-11.jpg")
mover("lukas-eSUXY2puRx0-unsplash.jpg", "local/local-salao-12.jpg")
mover("robert-vasquez-wPkqCFhlBXE-unsplash.jpg", "local/local-salao-13.jpg")
mover("steven-van-elk-KlEZTPp3csI-unsplash.jpg", "local/local-salao-14.jpg")
mover("steven-van-elk-NSvk6CEvv9Q-unsplash.jpg", "local/local-salao-15.jpg")
mover("taylor-gray-0L6wAmOJry8-unsplash.jpg", "local/local-salao-16.jpg")
mover("tyke-jones-lEQ_C-Rjk04-unsplash.jpg", "local/local-salao-17.jpg")
mover("pedro-pulido-PEMmaPY3IT8-unsplash.jpg", "local/local-sitio-1.jpg")
mover("ben-atkins-vcshPRvJpwo-unsplash.jpg", "local/local-jardim-1.jpg")
mover("bernie-almanzar-cZZ8D_wGI5Y-unsplash.jpg", "local/local-jardim-2.jpg")
mover("jaakko-perala-norway-elopement-photographer-u0bnFmPQrYo-unsplash.jpg", "local/local-jardim-3.jpg")
mover("matthew-essman-jTnipV64uLo-unsplash.jpg", "local/local-jardim-4.jpg")
mover("oliver-sherwin-VSO2Jktfmkw-unsplash.jpg", "local/local-jardim-5.jpg")
mover("grace-o-driscoll-cYMAb6eHQko-unsplash.jpg", "local/local-default-1.jpg")

# ========== ALIMENTAÇÃO ==========
mover("godz1-djgzRqYoLic-unsplash.jpg", "alimentacao/bolo-casamento-1.jpg")
mover("alexander-mass-Of_MqmuHOIE-unsplash.jpg", "alimentacao/bolo-casamento-2.jpg")
mover("jacques-dillies-_q0Y-l4xmhQ-unsplash.jpg", "alimentacao/bolo-casamento-3.jpg")
mover("junior-reis-EeJtg66OGa4-unsplash.jpg", "alimentacao/bolo-casamento-4.jpg")
mover("oyemike-princewill-bchR_kKwLdQ-unsplash.jpg", "alimentacao/bolo-casamento-5.jpg")
mover("vitor-monthay-JL2n-GWXCJo-unsplash.jpg", "alimentacao/bolo-casamento-6.jpg")
mover("adi-albulescu-wyTrSHeGwJ8-unsplash.jpg", "alimentacao/mesa-doces-1.jpg")
mover("aleksandra-sapozhnikova-asQ3m8WtBDc-unsplash.jpg", "alimentacao/mesa-doces-2.jpg")
mover("filipp-romanovski-m84P2Zdqr98-unsplash.jpg", "alimentacao/mesa-doces-3.jpg")
mover("fotografo-samuel-cruz-Fbt10XcA63M-unsplash.jpg", "alimentacao/mesa-doces-4.jpg")
mover("fotografo-samuel-cruz-xbn35s9dWH4-unsplash.jpg", "alimentacao/mesa-doces-5.jpg")
mover("hanxiao-xu-sKhZJhgqO8o-unsplash.jpg", "alimentacao/mesa-doces-6.jpg")
mover("jason-gardner-731BJV1VhKk-unsplash.jpg", "alimentacao/mesa-doces-7.jpg")
mover("joeyy-lee-3ctY-H53170-unsplash.jpg", "alimentacao/mesa-doces-8.jpg")
mover("jordan-arnold-Ul07QK2AR-0-unsplash.jpg", "alimentacao/mesa-doces-9.jpg")
mover("kostiantyn-vierkieiev-pdiGqa-5dJk-unsplash.jpg", "alimentacao/mesa-doces-10.jpg")
mover("lisandro-garcia-UR_SbilElPs-unsplash.jpg", "alimentacao/mesa-doces-11.jpg")
mover("luisa-brimble-ZRktbECxPFA-unsplash.jpg", "alimentacao/mesa-doces-12.jpg")
mover("shoham-avisrur-0AO1S25tSwM-unsplash.jpg", "alimentacao/mesa-doces-13.jpg")
mover("stella-de-smit-raE26Th7NwE-unsplash.jpg", "alimentacao/mesa-doces-14.jpg")
mover("visual-karsa-GvkI1rkNl6g-unsplash.jpg", "alimentacao/mesa-doces-15.jpg")
mover("zhouxing-lu-LvSDR31F_Vc-unsplash.jpg", "alimentacao/mesa-doces-16.jpg")
mover("jason-leung-uM3fwv4k6kY-unsplash.jpg", "alimentacao/coquetel-drinks-1.jpg")
mover("lola-azizada-jwN4ZZMunug-unsplash.jpg", "alimentacao/coquetel-drinks-2.jpg")
mover("taylor-flowe-5Txrg2kz7wQ-unsplash.jpg", "alimentacao/coquetel-drinks-3.jpg")
mover("majdah-majed-uQWCXh6_DNQ-unsplash.jpg", "alimentacao/bem-casados-1.jpg")

# ========== ENTRETENIMENTO ==========
mover("asdrubal-luna-DQZMol8wKm4-unsplash.jpg", "entretenimento/pista-danca-1.jpg")
mover("jamie-coupaud-wr8JCi35kz8-unsplash.jpg", "entretenimento/pista-danca-2.jpg")
mover("kari-bjorn-photography-bXoOQpB4MTg-unsplash.jpg", "entretenimento/pista-danca-3.jpg")
mover("taylor-heery--_tUHvw09jY-unsplash.jpg", "entretenimento/pista-danca-4.jpg")
mover("tony-eight-media--uZNyLofoPw-unsplash.jpg", "entretenimento/pista-danca-5.jpg")
mover("balint-henter-Uhml-IMBDok-unsplash.jpg", "entretenimento/dj-banda-1.jpg")
mover("max-letek-_zH2qqQ1dHA-unsplash.jpg", "entretenimento/dj-banda-2.jpg")
mover("asdrubal-luna-rFgwS07y1A4-unsplash.jpg", "entretenimento/cabine-fotos-1.jpg")
mover("sincerely-media-XVdAeTzv-oA-unsplash.jpg", "entretenimento/cabine-fotos-2.jpg")

# ========== BELEZA ==========
mover("anita-austvika-TPtAQFWZ2Jg-unsplash.jpg", "beleza/making-of-noiva-1.jpg")
mover("ashley-kaneko-Ay8fbR49Egk-unsplash.jpg", "beleza/making-of-noiva-2.jpg")
mover("briana-autran-LA9s_6cEYWA-unsplash.jpg", "beleza/making-of-noiva-3.jpg")
mover("brooke-balentine-CYP5vVw8Rjo-unsplash.jpg", "beleza/making-of-noiva-4.jpg")
mover("daniel-velasquez-d0gmEjrFhr0-unsplash.jpg", "beleza/making-of-noiva-5.jpg")
mover("didi-paul-xSMR2tM1dmE-unsplash.jpg", "beleza/making-of-noiva-6.jpg")
mover("emily-studer-OuMOV-W2S98-unsplash.jpg", "beleza/making-of-noiva-7.jpg")
mover("ephe-n-E2uuphQtc0Q-unsplash.jpg", "beleza/making-of-noiva-8.jpg")
mover("fotografo-samuel-cruz-_EgB4RJryTY-unsplash.jpg", "beleza/making-of-noiva-9.jpg")
mover("frames-for-your-heart-2sKs47PcCAk-unsplash.jpg", "beleza/making-of-noiva-10.jpg")
mover("gift-habeshaw-FgN7IJCAYvc-unsplash.jpg", "beleza/making-of-noiva-11.jpg")
mover("hannah-busing-URVe89DA5Cw-unsplash.jpg", "beleza/making-of-noiva-12.jpg")
mover("jabari-timothy-44fwSQE6ytg-unsplash.jpg", "beleza/making-of-noiva-13.jpg")
mover("jane-duursma-6FA5TPTM1-I-unsplash.jpg", "beleza/making-of-noiva-14.jpg")
mover("jonathan-borba--3I06f5rdL4-unsplash.jpg", "beleza/making-of-noiva-15.jpg")
mover("jonathan-borba-7rGfDGs5dE4-unsplash.jpg", "beleza/making-of-noiva-16.jpg")
mover("jonathan-borba-FptxMKxKwiE-unsplash.jpg", "beleza/making-of-noiva-17.jpg")
mover("jonathan-borba-HbpzUjv1wTU-unsplash.jpg", "beleza/making-of-noiva-18.jpg")
mover("jonathan-borba-QvprbCoOkLY-unsplash.jpg", "beleza/making-of-noiva-19.jpg")
mover("jonathan-borba-tiIqEDv03kM-unsplash.jpg", "beleza/making-of-noiva-20.jpg")
mover("katelyn-macmillan-5VhSc5jCA2g-unsplash.jpg", "beleza/making-of-noiva-21.jpg")
mover("katelyn-macmillan-ExjpauryqzA-unsplash.jpg", "beleza/making-of-noiva-22.jpg")
mover("malia-moore-7PuxGo267Bw-unsplash.jpg", "beleza/making-of-noiva-23.jpg")
mover("michael-demarco-1AJH6N6n4Ac-unsplash.jpg", "beleza/making-of-noiva-24.jpg")
mover("milla-huyskens-efltryiE8ZA-unsplash.jpg", "beleza/making-of-noiva-25.jpg")
mover("nadia-valko-0hAdietsUrE-unsplash.jpg", "beleza/making-of-noiva-26.jpg")
mover("nonik-bela-nZTrFceAr_U-unsplash.jpg", "beleza/making-of-noiva-27.jpg")
mover("pratham-kumar-DII41EMhy3E-unsplash.jpg", "beleza/making-of-noiva-28.jpg")
mover("samia-liamani-HGl1Q2Y-mbw-unsplash.jpg", "beleza/making-of-noiva-29.jpg")
mover("sergio-butko-f-AFdkhAk0I-unsplash.jpg", "beleza/making-of-noiva-30.jpg")
mover("sina-rezakhani-4saPMdy3bVU-unsplash.jpg", "beleza/making-of-noiva-31.jpg")
mover("tamara-govedarovic-Dcug-1cZymU-unsplash.jpg", "beleza/making-of-noiva-32.jpg")
mover("the-now-time-MA2A-5pRnsU-unsplash.jpg", "beleza/making-of-noiva-33.jpg")
mover("the-now-time-P2HUVoJFTX8-unsplash.jpg", "beleza/making-of-noiva-34.jpg")
mover("tron-le-PEnHcPYVeOA-unsplash.jpg", "beleza/making-of-noiva-35.jpg")
mover("vika-fleysher-mJuiGg87f-Y-unsplash.jpg", "beleza/making-of-noiva-36.jpg")
mover("andreea-avramescu-tyjaGZwYUtU-unsplash.jpg", "beleza/maquiagem-noiva-1.jpg")
mover("chulpan-gallyamova-PNsesXOdn2g-unsplash.jpg", "beleza/maquiagem-noiva-2.jpg")
mover("ellen-volkova-eRy9FIAHvOA-unsplash.jpg", "beleza/maquiagem-noiva-3.jpg")
mover("kristina-kutlesa-IxKTpb8XKH0-unsplash.jpg", "beleza/maquiagem-noiva-4.jpg")
mover("maryam-rostami-RzMb_2cGFkU-unsplash.jpg", "beleza/maquiagem-noiva-5.jpg")
mover("orliisa-TVu1kRyoOo8-unsplash.jpg", "beleza/maquiagem-noiva-6.jpg")
mover("previn-samuel-BY-Xn705Jfc-unsplash.jpg", "beleza/maquiagem-noiva-7.jpg")
mover("alexander-mass-RpoIAa93RXo-unsplash.jpg", "beleza/acessorios-noiva-1.jpg")
mover("caroline-attilio-je6xWZS2N08-unsplash.jpg", "beleza/acessorios-noiva-2.jpg")
mover("dyu-ha-wzIr03sTyHw-unsplash.jpg", "beleza/acessorios-noiva-3.jpg")
mover("emmalee-couturier-ciX9fOHgmik-unsplash.jpg", "beleza/acessorios-noiva-4.jpg")
mover("kelsey-booth-iZlVIHqZJqE-unsplash.jpg", "beleza/acessorios-noiva-5.jpg")
mover("marina-abrosimova-S-T0FPEnGZM-unsplash.jpg", "beleza/acessorios-noiva-6.jpg")
mover("550park-luxury-wedding-films-DPs4XTZXvhU-unsplash.jpg", "beleza/madrinhas-1.jpg")
mover("fotografo-samuel-cruz-GqmPjmfpmxo-unsplash.jpg", "beleza/madrinhas-2.jpg")
mover("kari-bjorn-photography-1r9J77ATMuM-unsplash.jpg", "beleza/madrinhas-3.jpg")
mover("milla-huyskens-g-tdTXC1VDE-unsplash.jpg", "beleza/madrinhas-4.jpg")
mover("sergio-butko-sGviXiOElPM-unsplash.jpg", "beleza/madrinhas-5.jpg")
mover("yan-berthemy-63CxrwDVeWE-unsplash.jpg", "beleza/madrinhas-6.jpg")
mover("lucas-t-photography-Dfm_QyLkIlw-unsplash.jpg", "beleza/making-of-noivo-1.jpg")

# ========== PAPELARIA ==========
mover("aaa-mm-bW3hz4eau1k-unsplash.jpg", "papelaria/convite-1.jpg")
mover("aaa-mm-xIoN-ZrESgY-unsplash.jpg", "papelaria/convite-2.jpg")
mover("adrianna-geo-cfsM9ZwU6II-unsplash.jpg", "papelaria/convite-3.jpg")
mover("danish-ali-JrAzVBf_ZNY-unsplash.jpg", "papelaria/convite-4.jpg")
mover("hazel-j-YQOdiIqlHEQ-unsplash.jpg", "papelaria/convite-5.jpg")
mover("matthew-idrt3RgujmQ-unsplash.jpg", "papelaria/convite-6.jpg")
mover("thomas-william-OAVqa8hQvWI-unsplash.jpg", "papelaria/convite-7.jpg")
mover("andy-holmes-cbe2y8SK2Xc-unsplash.jpg", "papelaria/menu-lugar-1.jpg")
mover("brett-jordan-gkpAyNvaB9w-unsplash.jpg", "papelaria/placa-boas-vindas-1.jpg")
mover("sketzo-store-XMaFaFMK0W8-unsplash.jpg", "papelaria/monograma-1.jpg")

# ========== DETALHES ==========
mover("aida-tavakkoli-ZFa7S1IvK4c-unsplash.jpg", "detalhes/buque-1.jpg")
mover("alexander-mass-j7LMXBkE3Pk-unsplash.jpg", "detalhes/buque-2.jpg")
mover("andres-molina-tucxUZ78XTI-unsplash.jpg", "detalhes/buque-3.jpg")
mover("cansu-hangul-4YpDdaK8S4o-unsplash.jpg", "detalhes/buque-4.jpg")
mover("cansu-hangul-sKvFd1Nzut8-unsplash.jpg", "detalhes/buque-5.jpg")
mover("corina-rainer-UHJCt2tyCPI-unsplash.jpg", "detalhes/buque-6.jpg")
mover("darrell-fraser-LKn-cFHir1M-unsplash.jpg", "detalhes/buque-7.jpg")
mover("diana-akhmedova-dSY3nSkRcDE-unsplash.jpg", "detalhes/buque-8.jpg")
mover("emam-hossan-shishir-i3741bxLpaE-unsplash.jpg", "detalhes/buque-9.jpg")
mover("engin-akyurt-i3rFV6ULk-o-unsplash.jpg", "detalhes/buque-10.jpg")
mover("fotografo-samuel-cruz-510Cm9UjUQU-unsplash.jpg", "detalhes/buque-11.jpg")
mover("fotografo-samuel-cruz-zdW5Xw_UK-Y-unsplash.jpg", "detalhes/buque-12.jpg")
mover("h-ng-xuan-van-bMGG7FKSISg-unsplash.jpg", "detalhes/buque-13.jpg")
mover("iacob-hiticas-y0MUwaHJm70-unsplash.jpg", "detalhes/buque-14.jpg")
mover("jennifer-kalenberg-nMoFmHqJnqo-unsplash.jpg", "detalhes/buque-15.jpg")
mover("jonathan-borba-ckNjKI5cH_E-unsplash.jpg", "detalhes/buque-16.jpg")
mover("jonathan-borba-u_q8rVK9lHE-unsplash.jpg", "detalhes/buque-17.jpg")
mover("kaja-reichardt-S3__pWlOEs8-unsplash.jpg", "detalhes/buque-18.jpg")
mover("katie-puzatova-kB-o4p3rY10-unsplash.jpg", "detalhes/buque-19.jpg")
mover("lauren-richmond-9bXKsMvgZtQ-unsplash.jpg", "detalhes/buque-20.jpg")
mover("mahsa-QjHwYGjBzYA-unsplash.jpg", "detalhes/buque-21.jpg")
mover("miltiadis-fragkidis-1Hc2PPb71QI-unsplash.jpg", "detalhes/buque-22.jpg")
mover("nicole-geri-hqCO0TYOeTU-unsplash.jpg", "detalhes/buque-23.jpg")
mover("olga-kononenko-zrQ51jFC2EQ-unsplash.jpg", "detalhes/buque-24.jpg")
mover("petr-ovralov-jNpttMRlb_Y-unsplash.jpg", "detalhes/buque-25.jpg")
mover("petr-ovralov-qQ01rvKkE0w-unsplash.jpg", "detalhes/buque-26.jpg")
mover("rj-trazona-ZPwuvBkXVj0-unsplash.jpg", "detalhes/buque-27.jpg")
mover("sam-galli-4QwnVtVXNzk-unsplash.jpg", "detalhes/buque-28.jpg")
mover("seif-eddin-khayat-59K3tJ_VwAw-unsplash.jpg", "detalhes/buque-29.jpg")
mover("sourabh-adhya-UFAtA_4khgE-unsplash.jpg", "detalhes/buque-30.jpg")
mover("t-k-i3NBcN0fJfg-unsplash.jpg", "detalhes/buque-31.jpg")
mover("taylor-heery-WCkclOUpeYQ-unsplash.jpg", "detalhes/buque-32.jpg")
mover("thomas-william-T4sn1Nw1f98-unsplash.jpg", "detalhes/buque-33.jpg")
mover("tom-kulczycki-IilKsqAemf4-unsplash.jpg", "detalhes/buque-34.jpg")
mover("vidit-goswami-9QvXCTB1Bdk-unsplash.jpg", "detalhes/buque-35.jpg")
mover("yishen-ji-bIQbD3JJByg-unsplash.jpg", "detalhes/buque-36.jpg")
mover("brittney-weng-IHFGvbBekOk-unsplash.jpg", "detalhes/aliancas-1.jpg")
mover("brittney-weng-Kc7b4smOmDk-unsplash.jpg", "detalhes/aliancas-2.jpg")
mover("brunxs-monochrome-ZpNBwBR38fA-unsplash (1).jpg", "detalhes/aliancas-3.jpg")
mover("christiann-koepke-1iI-QenyjQI-unsplash.jpg", "detalhes/aliancas-4.jpg")
mover("deepak-koyilada-NbQQ07fKIZQ-unsplash.jpg", "detalhes/aliancas-5.jpg")
mover("dickson-ngeno-QWWeOuJ_PpE-unsplash.jpg", "detalhes/aliancas-6.jpg")
mover("duo-chen-zeXp39YYR-s-unsplash.jpg", "detalhes/aliancas-7.jpg")
mover("fallon-michael-CEKa-wh1Fsw-unsplash.jpg", "detalhes/aliancas-8.jpg")
mover("fotografo-samuel-cruz-y5S8xA76JMw-unsplash.jpg", "detalhes/aliancas-9.jpg")
mover("hannah-busing-rYWEj9Cyx7E-unsplash.jpg", "detalhes/aliancas-10.jpg")
mover("ivonne-adame-6Hu3aJNdEV4-unsplash.jpg", "detalhes/aliancas-11.jpg")
mover("jennifer-kalenberg-Rkj0ms67lio-unsplash.jpg", "detalhes/aliancas-12.jpg")
mover("joeyy-lee-tkRlOnPtF4c-unsplash.jpg", "detalhes/aliancas-13.jpg")
mover("jonathan-borba-HKes9_amYnE-unsplash.jpg", "detalhes/aliancas-14.jpg")
mover("jonathan-borba-Y-uGpJBZONQ-unsplash.jpg", "detalhes/aliancas-15.jpg")
mover("katrien-sterckx-fn0xXL9szcU-unsplash.jpg", "detalhes/aliancas-16.jpg")
mover("norbert-braun-YAiNTtB8EjQ-unsplash.jpg", "detalhes/aliancas-17.jpg")
mover("peter-bucks-AITIEgEp9Cs-unsplash.jpg", "detalhes/aliancas-18.jpg")
mover("ranurte-1JWBEh6ILa4-unsplash.jpg", "detalhes/aliancas-19.jpg")
mover("rodrigo-rodrigues-wolf-r-t-Hz4u7Hd_VPE-unsplash.jpg", "detalhes/aliancas-20.jpg")
mover("tania-miron-ZJ0v_P0LJJw-unsplash.jpg", "detalhes/aliancas-21.jpg")
mover("vidit-goswami-DU7-Iz9LDs4-unsplash.jpg", "detalhes/aliancas-22.jpg")
mover("beatriz-perez-moya-SXHOGEudn7k-unsplash.jpg", "detalhes/sapatos-noiva-1.jpg")
mover("fabio-guntur-qG2yK_iNspE-unsplash.jpg", "detalhes/sapatos-noiva-2.jpg")
mover("gabriel-crismariu-JM4uYDCcYyw-unsplash.jpg", "detalhes/sapatos-noiva-3.jpg")
mover("gabriel-crismariu-G_mdr3kc4IY-unsplash.jpg", "detalhes/sapatos-noiva-4.jpg")
mover("jonathan-borba-b_y9pi-Rbqs-unsplash.jpg", "detalhes/sapatos-noiva-5.jpg")
mover("jonathan-borba-HabFYy1Iic0-unsplash.jpg", "detalhes/sapatos-noiva-6.jpg")
mover("jonathan-borba-Qjs6OI2KdTk-unsplash.jpg", "detalhes/sapatos-noiva-7.jpg")
mover("katie-puzatova-X7lE3-WSqxU-unsplash.jpg", "detalhes/sapatos-noiva-8.jpg")
mover("lauren-richmond-DnOgzmRYFeg-unsplash.jpg", "detalhes/sapatos-noiva-9.jpg")
mover("mk-s-KGDVTn9lYDE-unsplash.jpg", "detalhes/sapatos-noiva-10.jpg")
mover("pixel-bee-ISD-UTh15AE-unsplash.jpg", "detalhes/sapatos-noiva-11.jpg")
mover("sandy-millar-8vaQKYnawHw-unsplash.jpg", "detalhes/sapatos-noiva-12.jpg")
mover("shardayyy-photography-fJzmPe-a0eU-unsplash.jpg", "detalhes/sapatos-noiva-13.jpg")
mover("tetiana-thiel-ZueZt8hMdvw-unsplash.jpg", "detalhes/sapatos-noiva-14.jpg")
mover("vidit-goswami-Qkm_DzPYiD4-unsplash.jpg", "detalhes/sapatos-noiva-15.jpg")
mover("alexander-mass-r4Fz5SkUISM-unsplash.jpg", "detalhes/carro-noivos-1.jpg")
mover("josh-felise-eM7ImFWd5JA-unsplash.jpg", "detalhes/carro-noivos-2.jpg")
mover("matthew-zAum6EF1-x8-unsplash.jpg", "detalhes/carro-noivos-3.jpg")
mover("timo-c-dinger-Z7jJ1OMYZZQ-unsplash.jpg", "detalhes/carro-noivos-4.jpg")
mover("anastasiia-chepinska-FHLFSMOMmdg-unsplash.jpg", "detalhes/velas-decoracao-1.jpg")
mover("alexander-mass-77-MNCbsotU-unsplash.jpg", "detalhes/lembrancinhas-1.jpg")
mover("aneta-voborilova-01skWZ7MfvA-unsplash.jpg", "detalhes/lembrancinhas-2.jpg")
mover("celine-druguet-mE795PNyWr4-unsplash.jpg", "detalhes/lembrancinhas-3.jpg")
mover("christopher-politano-1ZuUTVKPJ_0-unsplash.jpg", "detalhes/lembrancinhas-4.jpg")
mover("film-PmAAQxEPw8Q-unsplash.jpg", "detalhes/lembrancinhas-5.jpg")
mover("harshil-gudka-_D1rKHYi9lc-unsplash.jpg", "detalhes/lembrancinhas-6.jpg")
mover("khalid-boutchich-MYmWkQsup-I-unsplash.jpg", "detalhes/lembrancinhas-7.jpg")
mover("luwadlin-bosman-P_HRPYpFTNA-unsplash.jpg", "detalhes/lembrancinhas-8.jpg")
mover("micah-sammie-chaffin-3jPeX2NaYIQ-unsplash.jpg", "detalhes/lembrancinhas-9.jpg")
mover("pedro-ed-ikr5H9j6o94-unsplash.jpg", "detalhes/lembrancinhas-10.jpg")
mover("vidit-goswami-uwf-zDMsbEw-unsplash.jpg", "detalhes/lembrancinhas-11.jpg")
mover("william-warby-PL3VrlEDqTM-unsplash.jpg", "detalhes/lembrancinhas-12.jpg")
mover("zara-walker-3hfDIJyGwic-unsplash.jpg", "detalhes/lembrancinhas-13.jpg")
mover("samantha-gades-JeEemtLSdjU-unsplash.jpg", "detalhes/detalhes-default-1.jpg")
mover("kai-nachtigal-YsgyGFZdEnI-unsplash.jpg", "detalhes/cadeiras-noivos-1.jpg")

print("")
print("=" * 44)
print("CONCLUÍDO")
print(f"Arquivos movidos: {movidos}")
print(f"Não encontrados: {nao_encontrados}")
print("=" * 44)