// utils/catalogoFornecedores.js
// Fonte única de verdade para categorias e serviços de fornecedores
// Importado por: painel do noivo, painel do cerimonialista, busca na plataforma

export const CATEGORIAS_FORNECEDORES = [
    { id: 'espaco_recepcao', label: 'Espaço e locação', sempre: true },
    { id: 'fotografia', label: 'Fotografia', sempre: true },
    { id: 'filmagem', label: 'Filmagem', sempre: true },
    { id: 'buffet', label: 'Buffet', sempre: true },
    { id: 'bebidas', label: 'Bebidas e bar', sempre: true },
    { id: 'decoracao', label: 'Decoração', sempre: true },
    { id: 'bolo_doces', label: 'Bolo e doces', sempre: true },
    { id: 'musica_festa', label: 'Música da festa', sempre: true },
    { id: 'transporte_noivos', label: 'Transporte dos noivos', sempre: true },
    { id: 'musica_cerimonia', label: 'Música da cerimônia', sempre: true },
    { id: 'oficializante_religioso', label: 'Oficializante religioso', condicao: 'cerimonia_religiosa' },
    { id: 'celebrante', label: 'Celebrante / Mestre de cerimônias', condicao: 'cerimonia_civil_simbolica' },
    { id: 'beleza_noiva', label: 'Beleza da noiva (cabelo e maquiagem)', condicao: 'tem_noiva' },
    { id: 'dia_noivo', label: 'Dia do noivo (barbearia)', condicao: 'tem_noivo' },
    { id: 'beleza_madrinhas', label: 'Beleza das madrinhas', condicao: 'tem_madrinhas' },
    { id: 'vestido_atelier', label: 'Vestido e ateliê', condicao: 'tem_noiva' },
    { id: 'traje_masculino', label: 'Traje masculino', condicao: 'tem_noivo' },
    { id: 'floricultura', label: 'Floricultura e arranjos', condicao: 'flores_confirmadas' },
    { id: 'iluminacao_cenica', label: 'Iluminação cênica', condicao: 'iluminacao_relevante' },
    { id: 'som_profissional', label: 'Som profissional', condicao: 'local_externo' },
    { id: 'dj', label: 'DJ', condicao: 'tem_dj' },
    { id: 'banda', label: 'Banda ao vivo', condicao: 'tem_banda' },
    { id: 'cabine_fotos', label: 'Cabine de fotos', condicao: 'tem_cabine_fotos' },
    { id: 'drone', label: 'Drone', condicao: 'tem_drone' },
    { id: 'cerimonialista', label: 'Assessoria e cerimonial', sempre: true },
    { id: 'papelaria', label: 'Papelaria e convites', condicao: 'convite_fisico_ou_hibrido' },
    { id: 'grafica', label: 'Gráfica', condicao: 'convite_fisico_ou_hibrido' },
    { id: 'geradores', label: 'Gerador de energia', condicao: 'local_sitio_externo' },
    { id: 'banheiros_extras', label: 'Banheiros extras', condicao: 'local_sitio_externo' },
    { id: 'mobiliario_locacao', label: 'Locação de mobiliário', condicao: 'mobiliario_especial' },
    { id: 'loucas_locacao', label: 'Locação de louças e talheres', condicao: 'loucas_especiais' },
    { id: 'seguranca', label: 'Segurança', condicao: 'muitos_convidados' },
    { id: 'transporte_convidados', label: 'Transporte de convidados', condicao: 'muitos_convidados_transporte' },
    { id: 'aliancas', label: 'Alianças', sempre: true },
    { id: 'bem_casados', label: 'Bem-casados e lembrancinhas', condicao: 'bem_casados_confirmados' },
    { id: 'bartender', label: 'Bartender e drinks autorais', condicao: 'tem_bartender' },
    { id: 'animacao_infantil', label: 'Animação infantil', condicao: 'tem_criancas' },
    { id: 'fornecedor_kosher', label: 'Fornecedor kosher', condicao: 'cerimonia_judaica' },
    { id: 'outro', label: 'Outro', sempre: true },
  ];
  
  export const SERVICOS_POR_CATEGORIA = {
    espaco_recepcao: [
      'Locação do espaço completo',
      'Locação apenas da cerimônia',
      'Locação apenas da recepção',
      'Locação do espaço + infraestrutura',
      'Day use',
    ],
    fotografia: [
      'Cobertura completa (cerimônia + festa)',
      'Cobertura da cerimônia',
      'Cobertura da festa',
      'Pré-wedding',
      'Ensaio noivado',
      'Making of noiva',
      'Making of noivo',
      'Cobertura completa + pré-wedding',
    ],
    filmagem: [
      'Cobertura completa (cerimônia + festa)',
      'Filme curto (highlight)',
      'Filme longo (documentary)',
      'Cobertura cerimônia',
      'Super 8 / analógico',
      'Cobertura completa + pré-wedding',
    ],
    buffet: [
      'Jantar empratado',
      'Jantar em buffet',
      'Estações de comida',
      'Coquetel + jantar',
      'Coquetel',
      'Food trucks',
      'Misto (buffet + estações)',
    ],
    bebidas: [
      'Open bar completo',
      'Open bar limitado (sem destilados)',
      'Espumante e refrigerantes',
      'Espumante, vinhos e refrigerantes',
      'Cerveja e refrigerantes',
      'Bartender + drinks autorais',
      'Bar sem álcool',
    ],
    decoracao: [
      'Decoração completa (cerimônia + festa)',
      'Decoração da cerimônia',
      'Decoração da festa',
      'Decoração floral',
      'Arranjos de mesa',
      'Backdrop para fotos',
      'Decoração + flores + mobiliário',
    ],
    bolo_doces: [
      'Bolo + mesa de doces',
      'Bolo',
      'Mesa de doces',
      'Naked cake',
      'Bolo fake + mesa de doces',
      'Cupcakes',
      'Mesa de doces finos',
    ],
    musica_festa: [
      'DJ',
      'Banda ao vivo',
      'Banda + DJ',
      'DJ com instrumentistas',
      'Playlist (sem contratação)',
    ],
    musica_cerimonia: [
      'Quarteto de cordas',
      'Duo (violino + piano)',
      'Coral',
      'Cantor solo',
      'Trio (violino, viola, cello)',
      'Piano solo',
      'Violão solo',
      'Violinista',
      'Música gravada',
    ],
    oficializante_religioso: [
      'Padre (católico)',
      'Pastor (evangélico)',
      'Rabino (judaico)',
      'Médium / guia espiritual (espírita)',
      'Oficializante de outra denominação',
    ],
    celebrante: [
      'Celebrante laico',
      'Juiz de paz (casamento civil)',
      'Mestre de cerimônias',
      'Celebrante + mestre de cerimônias',
    ],
    beleza_noiva: [
      'Cabelo + maquiagem (dia da noiva)',
      'Maquiagem',
      'Cabelo',
      'Penteado',
      'Dia da noiva completo (cabelo, maquiagem, unhas)',
    ],
    dia_noivo: [
      'Barbearia + corte',
      'Barba',
      'Corte + barba',
      'Hidratação facial',
    ],
    beleza_madrinhas: [
      'Maquiagem das madrinhas',
      'Cabelo das madrinhas',
      'Cabelo + maquiagem das madrinhas',
      'Pacote madrinhas + noiva',
    ],
    vestido_atelier: [
      'Vestido sob medida',
      'Vestido de pronta-entrega',
      'Vestido + acessórios',
      'Aluguel de vestido',
      'Jumpsuit',
      'Vestido midi',
      'Vestido de noivado',
    ],
    traje_masculino: [
      'Terno sob medida',
      'Terno alugado',
      'Smoking',
      'Blazer + calça',
      'Terno + colete',
      'Conjunto padrinhos',
    ],
    floricultura: [
      'Flores cerimônia + festa',
      'Flores cerimônia',
      'Flores festa (mesas)',
      'Buquê da noiva',
      'Buquê + arranjos',
      'Flores suspensas',
      'Flores secas',
      'Flores cerimônia + festa + buquê',
    ],
    iluminacao_cenica: [
      'Iluminação completa (cerimônia + festa)',
      'Iluminação pista de dança',
      'Iluminação ambiente',
      'Iluminação cerimônia',
      'Iluminação + efeitos especiais',
      'Projeção mapeada',
      'Canhões de luz',
      'Iluminação externa',
    ],
    som_profissional: [
      'Som completo (cerimônia + festa)',
      'Som da cerimônia',
      'Som da festa',
      'Mesa de som + técnico',
    ],
    dj: [
      'DJ completo (cerimônia + festa)',
      'DJ festa',
      'DJ + iluminação',
      'DJ + som',
      'DJ + cabine de fotos',
    ],
    banda: [
      'Banda completa',
      'Banda + DJ',
      'Banda cerimônia',
      'Banda festa',
      'Samba ao vivo',
      'MPB ao vivo',
      'Pop/rock ao vivo',
      'Jazz ao vivo',
    ],
    cabine_fotos: [
      'Cabine de fotos digital',
      'Cabine de fotos impressa',
      'Totem de fotos',
      'GIF booth',
      '360° booth',
      'Espelho mágico',
    ],
    drone: [
      'Cobertura aérea (foto + vídeo)',
      'Cobertura aérea (vídeo)',
      'Cobertura aérea (foto)',
      'Piloto de drone + edição',
    ],
    cerimonialista: [
      'Assessoria completa',
      'Assessoria parcial',
      'Cerimonial do dia',
      'Consultoria de planejamento',
      'Assessoria + cerimonial',
    ],
    papelaria: [
      'Convites físicos',
      'Convites digitais',
      'Convites físicos + digitais',
      'Save the date',
      'Convites + papelaria do evento (menus, plaquinhas)',
      'Papelaria completa do evento',
      'Monograma / identidade visual',
    ],
    grafica: [
      'Impressão de convites',
      'Impressão de papelaria do evento',
      'Envelopes e acabamentos',
      'Impressão + acabamento premium',
    ],
    geradores: [
      'Gerador completo',
      'Gerador de apoio',
      'Gerador + técnico de plantão',
    ],
    banheiros_extras: [
      'Banheiro químico',
      'Banheiro container executivo',
      'Banheiro trailer premium',
    ],
    mobiliario_locacao: [
      'Cadeiras',
      'Mesas',
      'Cadeiras + mesas',
      'Lounge completo',
      'Mobiliário cerimônia',
      'Mobiliário completo (cerimônia + festa)',
      'Altar + passarela',
      'Tendas',
    ],
    loucas_locacao: [
      'Louças completas',
      'Talheres',
      'Taças e copos',
      'Sousplats',
      'Louças + talheres + taças',
      'Louças premium',
    ],
    seguranca: [
      'Segurança do evento',
      'Portaria',
      'Controle de acesso',
      'Segurança + portaria',
    ],
    transporte_convidados: [
      'Van / ônibus fretado',
      'Transfer aeroporto',
      'Transporte completo de convidados',
      'Valet',
    ],
    transporte_noivos: [
      'Carro clássico',
      'Carro de luxo',
      'Limousine',
      'Carro personalizado',
      'Helicóptero',
      'Van decorada',
    ],
    aliancas: [
      'Alianças em ouro',
      'Alianças em prata',
      'Alianças em platina',
      'Alianças personalizadas',
      'Alianças + certificado de origem',
    ],
    bem_casados: [
      'Bem-casados tradicionais',
      'Bem-casados gourmet',
      'Caixinhas personalizadas',
      'Lembrancinhas personalizadas',
      'Bem-casados + embalagem personalizada',
    ],
    bartender: [
      'Bartender + drinks autorais',
      'Bar completo (bartender + insumos)',
      'Bartender + show de barismo',
      'Drinks autorais sem álcool',
    ],
    animacao_infantil: [
      'Monitor de crianças',
      'Recreação infantil',
      'Espaço kids com monitores',
      'Animação + espaço kids',
    ],
    fornecedor_kosher: [
      'Buffet kosher',
      'Certificação kosher',
      'Confeitaria kosher',
      'Bebidas kosher',
    ],
    outro: [],
  };
  
  export const STATUS_FORNECEDOR = [
    { id: 'a_contratar', label: 'A contratar', color: '#8B6F5E' },
    { id: 'negociando', label: 'Em negociação', color: '#F9A825' },
    { id: 'contratado', label: 'Contratado', color: '#2E7D32' },
    { id: 'pago', label: 'Pago', color: '#00838F' },
    { id: 'cancelado', label: 'Cancelado', color: '#C62828' },
  ];